Repository adranuz/hr-frontend, pull requests merged in 2023-03, with the labels that each got.

#97 Holidays crud
  src/api/interfaces/contingencies/contingency.interfaces.d.ts
  src/api/interfaces/holidays/catalogue-holidays.interface.d.ts
  src/api/interfaces/index.d.ts
  src/components/buttons/Buttons.tsx
  src/components/inputs/InputDatePicker.tsx
  src/components/modals/ModalEdit.tsx
  src/components/modals/ModalInfo.tsx
  src/components/shared/CommonForm.tsx
  src/helpers/formatDate.ts
  src/hooks/index.ts
  src/hooks/useHolidaysCatalogue.tsx
  src/hooks/useModal.tsx
  src/navigation/Navigation.tsx
  src/pages/employees/table-designs-employeeinfo/contingency-employeeinfo.tsx
  src/pages/history/History.tsx
  src/pages/holidays/Holidays.tsx
  src/pages/holidays/HolidaysCatalogue.tsx
  src/pages/holidays/HolidaysRegister.tsx
  src/pages/holidays/index.ts
  src/pages/holidays/table-design-holidays/columns.tsx
  src/pages/holidays/table-design-holidays/registerColums.tsx
  src/pages/index.tsx
  src/pages/request/table-design/other-columns.tsx
Labels: help wanted, fix

#98 Presentation
  src/components/modals/ModalEdit.tsx
  src/pages/holidays/Holidays.tsx
Labels: bug

#100 fix: :art: fix grammar mistake
  src/components/header-employee-info/HeaderEmployeeInfo.tsx
  src/components/section-employee-info/SectionEmployeeInfo.tsx
Labels: fix

#101 Quit halfday
  src/api/interfaces/contingencies/contingency.interfaces.d.ts
  src/components/form/ContingencyForm.tsx
  src/components/form/interfaces/contingencyForm.interfaces.d.ts
  src/components/modals/ModalEdit.tsx
  src/components/modals/ModalInfo.tsx
  src/components/modals/ModalReject.tsx
  src/hooks/useContingency.tsx
  src/pages/request/table-design/other-columns.tsx
Labels: bug
