Repository adranuz/hr-frontend, pull requests merged in 2023-01, with the labels that each got.

#18 Modalcontingency#11
  package.json
  src/components/form/ContingencyForm.css
  src/components/form/ContingencyForm.tsx
  src/pages/request/Request.tsx
  yarn.lock
Labels: enhancement

#21 Setstepperinmodal#19
  package.json
  src/components/card-action-container/CardActionContainer.css
  src/components/index.ts
  src/components/request-step/LastStep.tsx
  src/components/request-step/StepOne.tsx
  src/components/request-step/Stepper.tsx
  src/components/requestStep/StepOne.tsx
  src/components/requestStep/Stepper.tsx
  src/hooks/index.ts
  src/hooks/useModal.tsx
  src/pages/request/Request.tsx
  yarn.lock
Labels: enhancement

#31 Seniority page layout
  src/pages/vacation_seniority/VacationSeniority.tsx
Labels: enhancement

#33 Loginpage#22
  package.json
  src/assets/bg_login.svg
  src/assets/logo_improving.svg
  src/assets/sign_in_ms.svg
  src/pages/index.tsx
  src/pages/login/Login.css
  src/pages/login/Login.tsx
  vite.config.ts
  yarn.lock
Labels: enhancement

#35 favicon and app title
  index.html
  public/improving_isotype_192x192.png
  public/improving_isotype_192x192.svg
  public/vite.svg
Labels: enhancement

#37 Drawer style logo and icons
  src/assets/isotype_improving.svg
  src/assets/logo_improving.png
  src/assets/logo_improving.svg
  src/components/layout/MainLayout.css
  src/components/layout/MainLayout.tsx
  src/components/menu-router/MenuRouter.tsx
Labels: enhancement

#38 Fix stepper names#34
  src/components/form/ContingencyForm.tsx
  src/components/form/VacationForm.tsx
  src/components/request-step/StepMid.tsx
  src/components/request-step/Stepper.tsx
Labels: enhancement, good first issue, fix

#41 Fix stepper names
  src/components/form/VacationForm.tsx
Labels: refactor

#44 Senioritypage#23
  src/pages/vacation_seniority/VacationSeniority.tsx
Labels: enhancement

#52 Functional login
  package.json
  src/App.tsx
  src/components/layout/MainLayout.tsx
  src/components/menu-router/MenuRouter.tsx
  src/contexts/AuthContext.interfaces.d.ts
  src/contexts/AuthContext.tsx
  src/navigation/Navigation.tsx
  src/pages/login/Login.tsx
  yarn.lock
Labels: enhancement

#55 Modal reject
  src/components/index.ts
  src/components/table-actions/RejectActionButton.tsx
  src/hooks/useModal.tsx
  src/pages/employees/EmployeeInfo.tsx
Labels: enhancement
