Repository adranuz/hr-frontend, pull requests merged in 2023-02, with the labels that each got.

#61 Pagination contingency employee
  src/components/form/ContingencyForm.tsx
  src/components/index.ts
  src/components/table/TableContingency.tsx
  src/helpers/formatDate.ts
  src/helpers/index.tsx
  src/pages/employees/EmployeeInfo.tsx
Labels: enhancement

#62 fix: :bug: change functional format to an object
  src/components/form/ContingencyForm.tsx
  src/components/inputs/InputDate.tsx
  src/helpers/formatDate.ts
  src/helpers/index.tsx
Labels: documentation

#66 Usage api seniority
  src/pages/holidays/Holidays.tsx
  src/pages/vacation_seniority/VacationSeniority.tsx
Labels: enhancement

#64 refactor: move status component from table
  src/components/index.ts
  src/components/status/Status.tsx
Labels: enhancement

#71 style: :art: add Loading to the seniority vacation table
  src/pages/holidays/Holidays.tsx
  src/pages/vacation_seniority/VacationSeniority.tsx
Labels: enhancement

#73 fix: :bug: correct grammar mistakes - and format table
  src/pages/employees/EmployeeInfo.tsx
  src/pages/request/Request.tsx
  src/pages/request/table-design/contingency-request.tsx
Labels: enhancement

#80 Pass to new modal structure
  src/components/form/ContingencyForm.tsx
  src/components/index.ts
  src/components/modals/ModalOpenRequest.tsx
  src/components/request-step/LastStep.tsx
  src/components/request-step/StepMid.tsx
  src/components/request-step/Stepper.tsx
  src/helpers/formatDate.ts
  src/helpers/index.tsx
  src/pages/employees/EmployeeInfo.tsx
Labels: bug, documentation, duplicate, enhancement, good first issue, fix

#83 Pass to new modal structure
  src/components/buttons/Buttons.tsx
  src/components/form/ContingencyForm.tsx
  src/components/form/VacationForm.tsx
  src/components/form/interfaces/common.interfaces.d.ts
  src/components/form/interfaces/contingencyForm.interfaces.d.ts
  src/components/form/interfaces/index.d.ts
  src/components/modals/ModalEdit.tsx
  src/components/modals/ModalInfo.tsx
  src/components/modals/ModalOpenRequest.tsx
  src/components/request-step/StepMid.tsx
  src/components/request-step/Stepper.tsx
  src/helpers/formatDate.ts
  src/helpers/index.tsx
  src/hooks/index.ts
  src/hooks/useContingency.tsx
  src/hooks/useRequestPage.tsx
  src/pages/employees/EmployeeInfo.tsx
  src/pages/employees/table-designs/contingency-employeeinfo.tsx
  src/pages/request/Request.tsx
  src/pages/request/table-design/first-column.tsx
  src/pages/request/table-design/last-column.tsx
  src/pages/request/table-design/other-columns.tsx
Labels: enhancement

#84 Block days date picker
  src/api/interfaces/contingency.interfaces.d.ts
  src/components/form/ContingencyForm.tsx
  src/components/inputs/InputDatePicker.tsx
  src/components/inputs/index.ts
  src/components/modals/ModalOpenRequest.tsx
  src/components/request-step/StepMid.tsx
  src/components/request-step/StepOne.tsx
  src/components/request-step/Stepper.tsx
  src/helpers/formatDate.ts
  src/helpers/index.tsx
  src/hooks/useContingency.tsx
  src/hooks/useStepper.tsx
  src/pages/employees/EmployeeInfo.tsx
Labels: bug

#85 feat: :zap: block to send only half day in contingency
  src/components/card-action.tsx/CardAction.tsx
  src/components/form/ContingencyForm.css
  src/components/form/ContingencyForm.tsx
  src/components/request-step/StepMid.tsx
  src/components/request-step/StepOne.tsx
  src/components/request-step/Stepper.tsx
  src/hooks/useContingency.tsx
Labels: duplicate, enhancement, fix

#89 icon standardization
  package.json
  src/components/buttons/Buttons.tsx
  src/components/section-employee-info/SectionEmployeeInfo.tsx
  src/pages/employees/table-designs-employeeinfo/last-column.tsx
  src/pages/employees/table-designs-employees/last-column.tsx
  yarn.lock
Labels: fix

#88 Edit contingency restrictions
  src/components/modals/ModalEdit.tsx
  src/pages/employees/EmployeeInfo.tsx
Labels: enhancement

#93 Colors theme
  src/App.tsx
  src/assets/improving_isotype.svg
  src/components/buttons/Buttons.tsx
  src/components/layout/MainLayout.css
  src/components/layout/MainLayout.tsx
  src/components/modals/ModalDelete.tsx
  src/theme/ThemeProvider.tsx
Labels: fix

#96 style: :lipstick: add color standardization in buttons
  src/components/buttons/Buttons.tsx
  src/components/index.ts
  src/components/modals/ModalDelete.tsx
  src/components/section-employee-info/SectionEmployeeInfo.tsx
  src/theme/ThemeProvider.tsx
Labels: refactor
